config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects, only: [:show, :index] do
    resources :subscriptions, only: [:new, :create]
  #  resources :messages, only: :index
  #  resources :polls, only: [:new, :create, :index]
  #  collection do
  #    get :favorites
  #  end
  #  resources :favorites, only: [:create, :destroy]
  end
  resource :portfolio, only: :show
  resources :chatrooms, only: :show do
    resources :messages, only: [:create]
    resources :polls, only: [:new, :create]
  end
  resources :polls, only: :show do
    resources :poll_options, only: :create
    resources :responses, only: :create
  end


  #GET	/quizzes/new(.:format)
  #POST	/quizzes(.:format)
  resources :quizzes, only: [:new, :create]
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :project
  has_many :messages, dependent: :destroy
  has_many :polls, dependent: :destroy
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end
end

app/views/chatrooms/show.html.erb
<div class="chatroom">
  <div class="container py-5">
    <div class="container card-project p-5 " style="filter: opacity(100%)">
      <div class="row justify-content-center">
        <h3 class="" >Investor room for <%= link_to @chatroom.project.name, project_path(@chatroom.project), class:"chatroom-header" %></h3>
      </div>
      <div id="messages" data-chatroom-id="<%= @chatroom.id %>">
        <% @chatroom.messages.each do |message| %>
          <div class="message-container mb-4" id="message-<%= message.id %>">
            <i class="author">
              <span><%= message.user.name %></span>
              <small><%= message.created_at.strftime("%a %b %e at %l:%M%p") %></small>
            </i>
            <p class="chatrom-content"><%= message.content %></p>
            <% if message.poll_id %>
              <% if message.poll.user == current_user %>
                <% if message.poll.responses.any? { |response| response.user == current_user} %>
                  <p><%= link_to "Edit the poll", poll_path(message.poll), class:"btn button-style" %></p>
                  <% message.poll.poll_options.each do |poll_option| %>
                    <%= poll_option.content %>:
                    <div class="progress" style="height: 20px;">
                      <div class="progress-bar" role="progressbar" style="width: <%= poll_option.responses.count %>%;" aria-valuenow= "<%= poll_option.responses.count %>" aria-valuemin="0" aria-valuemax="2"><%= poll_option.responses.count %></div>
                    </div>
                  <% end %>
                <% else %>
                  <p><%= link_to "Edit Or Vote", poll_path(message.poll), class:"btn button-style" %></p>
                <% end %>
              <% else %>
                <% if message.poll.responses.any? { |response| response.user == current_user} %>
                  <p><%= link_to "You have already voted", "", class:"btn button-style" %></p>
                  <% message.poll.poll_options.each do |poll_option| %>
                    <%= poll_option.content %>:
                    <div class="progress" style="height: 20px;">
                      <div class="progress-bar" role="progressbar" style="width: <%= poll_option.responses.count %>%;" aria-valuenow= "<%= poll_option.responses.count %>" aria-valuemin="0" aria-valuemax="2"><%= poll_option.responses.count %></div>
                    </div>
                  <% end %>
                <% else %>
                  <p><%= link_to "Participate", poll_path(message.poll), class:"btn button-style" %></p>
                <% end %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="">
          <%= simple_form_for [@chatroom, @message], remote: true do |f| %>
            <%= f.input :content, label: false, placeholder: "Message #{@chatroom.project.name}" %>
        <div class="row d-flex justify-content-between">
            <%= f.button :submit, class:"btn button-style w-25" %>
            <%= link_to "Create a poll", new_chatroom_poll_path(@chatroom), class:"btn button-style w-25" %>
            <%= link_to "Back to project", @chatroom.project, class:"btn button-style w-25" %>
          </div>
      </div>
      <% end %>
    </div>
  </div>
</div>