config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects, only: [:show, :index] do
    resources :subscriptions, only: [:new, :create]
  #  resources :messages, only: :index
  #  resources :polls, only: [:new, :create, :index]
  #  collection do
  #    get :favorites
  #  end
  #  resources :favorites, only: [:create, :destroy]
  end
  resource :portfolio, only: :show
  resources :chatrooms, only: :show do
    resources :messages, only: [:create]
    resources :polls, only: [:new, :create]
  end
  resources :polls, only: :show do
    resources :poll_options, only: :create
    resources :responses, only: :create
  end


  #GET	/quizzes/new(.:format)
  #POST	/quizzes(.:format)
  resources :quizzes, only: [:new, :create]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon shadow-sm">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://image.freepik.com/free-vector/3d-isometric-cube_119708-18.jpg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item active text-center " style="width: 5.5rem">
          <%= link_to "Projects", projects_path, class: "btn"%>
        </li>
        <li class="nav-item active text-center mx-4" style="width: 5.5rem">
          <%= link_to "Portfolio", portfolio_path, class: "btn"%>
        </li>
        <li class="nav-item active text-center mx-4" style="width: 5.5rem">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn"%>
        </li>
        <li class="nav-item dropdown ">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>