config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects, only: [:show, :index] do
    resources :subscriptions, only: [:new, :create]
  #  resources :messages, only: :index
  #  resources :polls, only: [:new, :create, :index]
  #  collection do
  #    get :favorites
  #  end
  #  resources :favorites, only: [:create, :destroy]
  end
  resource :portfolio, only: :show
  resources :chatrooms, only: :show do
    resources :messages, only: [:create]
    resources :polls, only: [:new, :create]
  end
  resources :polls, only: :show do
    resources :poll_options, only: :create
    resources :responses, only: :create
  end


  #GET	/quizzes/new(.:format)
  #POST	/quizzes(.:format)
  resources :quizzes, only: [:new, :create]
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :cash_yields, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :users, through: :subscriptions
  has_many :investment_highlights
  has_one :chatroom, dependent: :destroy
  has_one_attached :banner_picture
  after_create :calc_surface
  after_create :create_chatroom

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def oversubscribed?(subscription)
    subscription.amount + subscriptions.sum(&:amount) > amount
  end

  def net_equity_multiple
    (cash_yields.sum(&:value) / amount).round(1)
  end

  def net_cash_yield
    (cash_yields.sum(&:value) / (amount * cash_yields.count)).round(4)
  end

  def percentage_subscribed
    (subscriptions.sum(&:amount) / amount).round(2)
  end

  def target_hold
    (maturity_date.year - start_date.year) - (maturity_date.month >= start_date.month ? 0 : 1)
  end

  def cash_yield_array
    irr_array = []
    cash_yields.each do |cash_yield|
      irr_array << [cash_yield.value, cash_yield.date]
    end
    irr_array
  end


  def target_net_irr
    irr_array = cash_yield_array
    bottom = 0
    top = 1
    iterations = 0
    npv = -amount
    until npv < amount * 0.000000001 && npv > -amount * 0.000000001
      range_average = (bottom + top).to_f / 2
      iterations += 1
      npv = -amount
      irr_array.each do |date_flow|
        npv += date_flow[0] / ((1 + range_average)**((date_flow[1] - start_date) / 365.25))
      end
      if npv.negative?
        top = range_average
      else
        bottom = range_average
      end
    end
    return (bottom + top) / 2
  end

  # SEARCH

  include PgSearch::Model
  pg_search_scope :search_by_name_location_description,
    against: [ :name, :location, :description],
    using: {
      tsearch: { prefix: true }
    }

  # SEARCH END

  private

  def create_chatroom
    Chatroom.create(project: self)
  end

  def calc_surface
    update surface: amount / (rand(0.8..1.2) * 10_000).round
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @projects = Project.all
    if params[:query].present?
      @projects = Project.search_by_name_location_description(params[:query])
    else
      @projects = Project.all
    end
    @markers = @projects.geocoded.map do |project|
      {
        lat: project.latitude,
        lng: project.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { project: project })
      }
    end
  end
  
  def show
    @project = Project.find(params[:id])
    @users = @project.users.distinct
    @pie_data = ChartkickMethods.pie_chart_method(@users, @project)
    @markers = 
      {
        lat: @project.latitude,
        lng: @project.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { project: @project })
        
      }
  end
end

app/views/projects/_info_window.html.erb
<div class="map-info-window">

  <%= cl_image_tag project.banner_picture.key, height: 120, width: 250, crop: :fill, class:"card-image mt-2" %>
  <p class="text-center"><%= link_to project.name, project, class:"map-popup-title text-cente"%></p>
  <p class="map-popup-text location text-center pb-2"><%= project.location %></p>
  <div class="container">
    <div class="row">
      <div class="col-6 "><p class="map-popup-numbers text-center"><%= (project.target_net_irr * 100).round(2) %>%</p>
        <p class="text-center">Target Net IRR</p></div>

      <div class="col-6 "><p class="map-popup-numbers text-center"><%= (project.net_cash_yield * 100).round(2) %>%</p>
        <p class="text-center">Net Cash Yield</p></div>
    </div>
    <div class="row">
      <div class="col-6 "><p class="map-popup-numbers text-center"><%= project.net_equity_multiple %>x</p>
        <p class="text-center">Net Equity Multiple</p></div>

      <div class="col-6 "><p class="map-popup-numbers text-center"><%= project.target_hold %> Years</p>
        <p class="text-center">Target Hold</p></div>
    </div>
    <%= link_to "See details", project, class:"btn button-style btn-sm btn-block" %>
  </div>
</div> 

app/views/projects/_list-of-cards.html.erb
  <div class="row d-flex justify-content-center ml-5 pl-5">
    <% @projects.each do |project| %>
      <% @project = project  %>
      <div class="col-lg-6 mb-5">
        <%= render partial: "projects/project-card", locals: { project: @project} %>
      </div>
    <% end %>
  </div>

app/views/projects/_map-card-index.html.erb
<% @project.longitude %>
<% @project.latitude %>
<% base_url = "https://api.mapbox.com/styles/v1/nikiforov5000/ckm3slb1razov17s5rzjbavhc/static/pin-s+dab483(#{@project.longitude},#{@project.latitude})/#{@project.longitude},#{@project.latitude},3/300x500?access_token=#{ENV['MAPBOX_API_KEY']}" %>
<img src="<%= base_url %>"
  class="card-map-image"
  alt="<%= @project.location %>">

app/views/projects/_map-show.html.erb
<% base_url = "https://api.mapbox.com/styles/v1/nikiforov5000/ckm3slb1razov17s5rzjbavhc/static/pin-s+dab483(#{@project.longitude},#{@project.latitude})/#{@project.longitude},#{@project.latitude},8/1000x500?access_token=#{ENV['MAPBOX_API_KEY']}" %>
<img src="<%= base_url %>"
  class="map-show"
  alt="<%= @project.location %>">

app/views/projects/_marker-for-index-map.html.erb
<div class="index-map-marker">
</div>

app/views/projects/_project-card.html.erb
<div class="card-project mr-0">
    <%= cl_image_tag @project.banner_picture.key, crop: :fill, class:"card-image" %>
    <h3 class="text-center card-title-project pt-3"><%= @project.name %></h3>
    <p class="text-center index-card-small-text"><%= @project.location %></p>

    <div class="row m-auto px-3">
      <div class="fin-stat col-6 text-center">
        <p class="numbers-index-page "><%= (@project.target_net_irr * 100).round(2) %>%</p>
        <p class="index-card-small-text mt-1">Target Net IRR</p>
      </div>
      <div class="fin-stat col-6 text-center">
        <p class="numbers-index-page "><%= (@project.net_cash_yield * 100).round(2) %>%</p>
        <p class="index-card-small-text mt-1">Net Cash Yield</p>
      </div>
    </div>

    <div class="row m-auto pt-0">
      <div class="fin-stat col-6 text-center">
        <p class="numbers-index-page "><%= @project.net_equity_multiple %>x</p>
        <p class="index-card-small-text mt-1">Net Equity Multiple</p>
      </div>
      <div class="fin-stat col-6 text-center">
        <p class="numbers-index-page "><%= @project.target_hold %> Years</p>
        <p class="index-card-small-text mt-1">Target Hold</p>
      </div>
    </div>

    <div class="progress" style="height: 8px;">
      <div class="progress-bar" role="progressbar" style="width: <%= @project.percentage_subscribed * 100 %>%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
    </div>

    <%= link_to "See details", @project, class:"btn-block btn button-style rounded-bottom" %>

</div>

app/views/projects/index.html.erb
<style type="text/css">
   body { background: white !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>
    <div class="row my-3 py-3">
      <div class="col-6">
        <%# Projects list %>
        <%= render partial: 'projects/list-of-cards', locales: { projects: @projects } %>
      </div>
    
      <div class="col-6 fixed" >
        <div class="container mb-3 py-3 bg-white mx-0 px-0">
          <%= form_tag projects_path, method: :get do %>
            <div class="row">
              <div class="col-8">
                <%= text_field_tag :query,
                  params[:query],
                  class: "form-control",
                  placeholder: "Farm name, crop, or location..." %>
              </div>
              <div class="col-4">
                <%= submit_tag "Search", class: "button-style-search h-100 w-100" %>
              </div>
              <% if @projects.empty? %>
                <p class="card-small-text"> no results with "<%= params[:query] %>", maybe try search for "apple"...</p>
              <% end %>
            </div>
          <% end %>
        </div>

        <%# MAP %>
        <div class="border">
        <div id="map"
          style="width: 100%; height: 100vh;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
        </div>
      </div>

    </div>

app/views/projects/show.html.erb
<style type="text/css">
   body { background: white !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>
<%# for meta %>
<% content_for :meta_title, "#{@project.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @project.description %>
<%# <% content_for :meta_image, cl_image_path(@project.photo.path) %>
<%# meta end %>

<%= cl_image_tag @project.banner_picture.key, crop: :fill, class:"show-banner" %>

<div class="container show-project p-5" style="filter: opacity(100%); margin-top: 15vh;">

  <div class="container pt-3" >
    <div class="row mb-2">
      <div class="col">
        <h1 class="title-project"><%= @project.name %></h1>
        <p class="project-location-text"><%= @project.location %></p>
      </div>

      <div class="col">
        <p class="project-location-text">Commited <%= @project.percentage_subscribed * 100 %>%</p>
        <div class="progress" style="height: 2rem;">
          <div class="progress-bar" role="progressbar" style="width: <%= @project.percentage_subscribed * 100 %>%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-12 col-md-6">
        <div class="row">
          <div class="fin-stat-show col bg-gradient">
            <p class="numbers-show"><%= (@project.target_net_irr * 100).round(2) %>%</p>
            <p class="card-small-text-fin">Target Net IRR</p>
          </div>
          <div class="fin-stat-show col bg-gradient">
            <p class="numbers-show"><%= (@project.net_cash_yield * 100).round(2) %>%</p>
            <p class="card-small-text-fin">Net Cash Yield</p>
          </div>
          <div class="fin-stat-show col bg-gradient">
            <p class="numbers-show"><%= @project.net_equity_multiple %>x</p>
            <p class="card-small-text-fin">Net Equity Multiple</p>
          </div>
        </div>
        <div class="row mt-3">
          <div class="fin-stat-show col bg-gradient">
            <p class="numbers-show"><%= @project.target_hold %> Years</p>
            <p class="card-small-text-fin">Target Hold</p>
          </div>
          <div class="fin-stat-show col bg-gradient">
            <p class="numbers-show"> $<%= @project.amount %></p>
            <p class="card-small-text-fin">Total</p>
          </div>
          <div class="fin-stat-show col bg-gradient">
            <p class="numbers-show"><%= @project.surface %> ac</p>
            <p class="card-small-text-fin">Land surface</p>
          </div>
        </div>
        <div class="row mt-3">
          <div class="fin-stat-show col bg-gradient">
            <p class="numbers-show"><%= @project.crop %></p>
            <p class="card-small-text-fin">Crop</p>
          </div>
          <div class="fin-stat-show col bg-gradient">
            <p class="numbers-show"><%= @project.start_date %></p>
            <p class="card-small-text-fin">Start date</p>
          </div>
          <div class="col bg-gradient">
            <p class="numbers-show"><%= @project.maturity_date %></p>
            <p class="card-small-text-fin">Maturity date</p>
          </div>
        </div>
        <div class="row mt-3">
          <p class="card-small-text-description "><%= @project.description %></p>
        </div>
      </div>
      <div class="col-12 col-md-6">
        <div class="container">
          <%= pie_chart @pie_data, suffix: "%",title: "Shares of investors", legend: "right", height: "400px", id: "pie-chart-show-project" %>
        </div>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col">
      <% if @project.funded == true %>
          <div class="btn btn-block bg-info" style="color: white;">The project was already subscribed</div>
        <% else %>
          <%= link_to "Subscribe", new_project_subscription_path(@project), class:"btn btn-block button-style-show-projects" %>
        <% end %>
    </div>
    <div class="col">
      <% if @project.subscriptions.any? { |subscription| subscription.user == current_user } %>
        <%= link_to "Access the chatroom", chatroom_path(@project.chatroom), class:"btn btn-block button-style-show-projects" %>
      <% end %>
    </div>
  </div>

    <%# MAP %>
   
    <%= render 'projects/map-show', locales: { project: @project } %>

</div>